### ISSUE TITLE
Minification

### ISSUE THREAD

**Issue by sseppola** [xuopled/react-google-maps-loader#4]
Hi, could you upload the source file as well as the minified script to npm?
I'm having some trouble with this module and trying to debug it, and it would be a lot easier with the source file.

Thanks for releasing this module.

**Comment by xuopled** [comment]
I don't have a lot of time these days. I will appreciate your help about this. Thank you :)

**Comment by jaydenseric** [comment]
NPM packages should not be minified at all, and ideally the source code is also published with source maps. Minification is done by the consumer of the package in their own project. This allows them to configure minification, and the process works better when doing the whole project at once. It also makes error traces in development easier to read.

**Comment by xuopled** [comment]
I agree, I should build the two files. Do you have examples of npm scripts / webpack config to do it easily ? Or maybe you can make a PR.

Thank you

**Comment by jaydenseric** [comment]
Here is a package I published recently using Rollup: https://github.com/jaydenseric/apollo-upload-client.

Note the `module` entry in the package.json – this allows ESM aware tools such as Rollup and Webpack 2 to do better destructured imports and dead code elimination.

Because this can run on server and client, you would also add `engines` to the package.json like [this](https://github.com/jaydenseric/apollo-upload-server/blob/master/package.json#L54) and add node to the `targets` for babel-preset-env like [this](https://github.com/jaydenseric/apollo-upload-server/blob/master/package.json#L63).

If this package is a good fit for my project over the next few days I can jump in and give you hand.

**Comment by xuopled** [comment]
Ok it looks interesting. 
I don't know the Rollup ecosystem so I'm not sure to want use it for this project

**Comment by jaydenseric** [comment]
Rollup does a good job for NPM packages with the best dead code elimination out there, they pioneered the whole `js:next`/`module` entry thing. It's also a lot easier to configure than webpack. Webpack 2 is still the best choice for actual projects due to the loaders ecosystem, ability to compile multiple (server/client) configs at once, code-splitting features etc.

**Comment by xuopled** [comment]
Ok good to know. Thank you

**Comment by xuopled** [comment]
The build was updated with the new v4.0.0. There is now ES6, AMD and CommonJS builds
